### ISSUE TITLE
Add an example & fix the code css

### ISSUE THREAD

**Issue by benpetersen** [techstreams/harp-github-markdown#2]
Please add an example that uses the classes, also, the code element didn't allow for white space and line endings to indicate a new line should be shown. Below is what it should be (or pretty close)

```
<div class="markdown-body">
<code>
var test = "";
var test2 = test;
</code>
</div>
```

github-markdown.css
```
.markdown-body code {
  padding: 0;
  padding-top: 0.2em;
  padding-bottom: 0.2em;
  margin: 0;
  font-size: 85%;
  background-color: rgba(0,0,0,0.04);
  display: block;
  border-radius: 3px;
  word-wrap: break-word;
  word-break: break-all;
  line-height:  1.42857143;
  white-space: pre-wrap;
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 20px;
}
```

**Comment by techstreams** [comment]
@benpetersen  The CSS has been updated to the latest from the [source project](https://github.com/sindresorhus/github-markdown-css).  If you have questions about the CSS itself, you'll want to refer to that project.

As for an example ... the classes are not intended to be used directly.  Instead add [markdown](https://guides.github.com/features/mastering-markdown/) to any `public/*.md` file and run the Harp server.  Harp will automatically convert the markdown to HTML and apply the `github-markdown.css` styles.  

To test ... add the following markdown to the `public/index.md` file in your local copy of this project and run the [Harp](http://harpjs.com/docs/) server.  You should see the code displayed appropriately in your browser -- `localhost:9000`

<pre>

## Here's a code block

```
var test = "";
var test2 = test;
```
</pre>

If you do use the `<code></code>` tag instead of using a markdown code block, you'll want to wrap it in a `<pre></pre>` tag to get the desired behavior. -- `<pre><code></code></pre>`

Hope that helps.
